### ISSUE TITLE
ServerSelector.Desktop.exe Cannot save

### ISSUE THREAD

**Issue by klszf** [MishaProductions/nikke-server#10]
![1720913646283](https://github.com/user-attachments/assets/5292a575-5e85-46ce-90e9-26c29ba4f096)
![1720913684751](https://github.com/user-attachments/assets/7b5f8ad3-0544-489c-baff-b51676fc05ac)

**Comment by MishaProductions** [comment]
Are you sure that the launcher path is correct?

**Comment by klszf** [comment]
> 您确定启动器路径正确吗？

Is it because I'm using the CN client?

**Comment by pzwboy** [comment]
港澳台端就将nikke_launcher_hmt.exe改名为nikke_launcher.exe就行了
