### ISSUE TITLE
Always need to re-login

### ISSUE THREAD

**Issue by wangyujie1025** [MishaProductions/nikke-server#13]
![image](https://github.com/user-attachments/assets/71c769e5-841f-438e-a528-863381c9be7c)
Well,it always asks me to re-login
![image](https://github.com/user-attachments/assets/a3f9212b-11b1-4404-8c0f-e47f351dbdc6)

**Comment by MishaProductions** [comment]
Try using the global version of the game instead of the HMT version

**Comment by wangyujie1025** [comment]
ok let me try first

**Comment by wangyujie1025** [comment]
[Player.log](https://github.com/user-attachments/files/16401022/Player.log)

**Comment by wangyujie1025** [comment]
are mods available

**Comment by MishaProductions** [comment]
There aren't any mods yet
