### ISSUE TITLE
Stuck at the loading screen 1/2 100%

### ISSUE THREAD

**Issue by RojiaKyoma** [MishaProductions/nikke-server#2]
![image](https://github.com/MishaProductions/nikke-server/assets/67216905/9e4258d8-2532-4e84-9dab-f92878d6f0e0)
here is the log
[Player.log](https://github.com/user-attachments/files/16104395/Player.log)

**Comment by MishaProductions** [comment]
Hello, can you check if 42261a16b6d985f184ef1e2be44c7a8a45b7d396 fixes this? Should fix this issue if you weren't using global server. Thanks!

**Comment by RojiaKyoma** [comment]
It works, thanks a lot.
