### ISSUE TITLE
Can not run serverselector.desktop.exe

### ISSUE THREAD

**Issue by cantrunserverselectordesktopexe** [MishaProductions/nikke-server#5]
forgive me for this stupid question, i have zero knowledge on github or code related stuff so I have no idea how to open the required file 
![Capture](https://github.com/MishaProductions/nikke-server/assets/175337260/740cd21a-7d38-4a29-892d-0bfc8e41f2ff)

**Comment by MishaProductions** [comment]
Hello, you can download the latest build here: https://github.com/MishaProductions/nikke-server/actions/runs/9892952935/artifacts/1691267490
