### ISSUE TITLE
Help Setting Things Up

### ISSUE THREAD

**Issue by Ecens** [MishaProductions/nikke-server#6]
![Screenshot 2024-07-12 054600](https://github.com/user-attachments/assets/f6d22eb4-7289-4897-bbd3-ba4f73986245)

![Screenshot 2024-07-12 054510](https://github.com/user-attachments/assets/afe11e5b-6ea8-489c-b5e3-6ecd42d9db3c)

![Screenshot 2024-07-12 054506](https://github.com/user-attachments/assets/07a212c1-de5d-4d53-9828-b8f6517054dd)
 
![nikkeserver](https://github.com/user-attachments/assets/b0539633-5dd4-43cb-9598-364ef6195d6b)

Im new to this so sorry for the inconvenience, i need some overall help bc i cant seem to get it done

**Comment by MishaProductions** [comment]
Should be fixed in latest release: https://github.com/MishaProductions/nikke-server/releases/tag/v0.1.1

**Comment by Ecens** [comment]
![image](https://github.com/user-attachments/assets/c39e868a-4c99-469f-b4dc-f1878d838237)

Is that what it should look like?

**Comment by MishaProductions** [comment]
Try running nksrv as admin

**Comment by Ecens** [comment]
I did, and it still showed me the same

**Comment by MishaProductions** [comment]
Are you sure that nothing is using ports 80 & 443? Also try allowing nksrv in Windows Firewall: https://stackoverflow.com/a/41340197

**Comment by Ecens** [comment]
![image](https://github.com/user-attachments/assets/b4be4d10-4620-4c68-90e0-4522052dbbdd)

My System is using Port 80

**Comment by MishaProductions** [comment]
Can you go to http://localhost:80 and check what shows up?

**Comment by Ecens** [comment]
![image](https://github.com/user-attachments/assets/48cbbab0-ba85-4814-bcd9-6467bb93520b)

You mean this?

**Comment by MishaProductions** [comment]
Can you go to optional features in Windows and disable "Internet Information Services"? Should allow nksrv to use port 80/443 as IIS is using it.

**Comment by MishaProductions** [comment]
Yeah it should be working now, try creating an account

**Comment by Ecens** [comment]
I did and it worked.

Thank you so much for your time and help

**Comment by MishaProductions** [comment]
No problem!
