### ISSUE TITLE
still 'static data download fail'

### ISSUE THREAD

**Issue by cgvote** [MishaProductions/nikke-server#7]
![屏幕截图 2024-07-13 002738](https://github.com/user-attachments/assets/391ffb73-b363-45a8-88cb-e6c696191606)
![屏幕截图 2024-07-13 003934](https://github.com/user-attachments/assets/60653f1c-428c-4ad8-a5eb-c35cbfab2bd8)
hello,Err,i dont know why it is still  'static data download fail'

**Comment by MishaProductions** [comment]
Should be fixed by c1d783b1e7476fba7368f59f1b1b9ce7519fc105, this problem occured because I hard coded the IP address for https://cloud.nikke-kr.com/ which might be different for you. Download it here: https://github.com/MishaProductions/nikke-server/actions/runs/9912210242
