### ISSUE TITLE
Stuck at IntSuccess 

### ISSUE THREAD

**Issue by Ecens** [MishaProductions/nikke-server#8]
![image](https://github.com/user-attachments/assets/61fc19a1-7ab0-49b8-9e57-6dd931ec3e97)

Hey, sorry to disturb again but im stuck at the 2/2 IntSuccess

**Comment by MishaProductions** [comment]
Can you please send `%appdata%..\LocalLow\com.proximabeta\NIKKE\player.log`?

**Comment by Ecens** [comment]
[Player.log](https://github.com/user-attachments/files/16198310/Player.log)

Here you go

**Comment by MishaProductions** [comment]
![image](https://github.com/user-attachments/assets/d2164838-6bc0-4ae8-922a-a9cb0a0b134f)
Try deleting all of the files in ```%appdata%\..\LocalLow\com_proximabeta\NIKKE```. Don't delete the folders. Those files are used as a cache which might be causing this issue.

**Comment by Ecens** [comment]
Nope, im still stuck

**Comment by Ecens** [comment]
It was all working earlier today, but after i had to restart my PC its stuck like this

**Comment by MishaProductions** [comment]
Which stage have you last completed?

**Comment by Ecens** [comment]
Chapter 2 to Unlock the Outpost

**Comment by Ecens** [comment]
So Chapter 2 20 I think it was

**Comment by MishaProductions** [comment]
Reproduced the issue, I think I know how to fix it

**Comment by Ecens** [comment]
Sounds great

**Comment by MishaProductions** [comment]
Should be fixed in latest commit now.

**Comment by Ecens** [comment]
So just redownload the 1.1 Release?

**Comment by MishaProductions** [comment]
Download this: https://github.com/MishaProductions/nikke-server/actions/runs/9913698080/artifacts/1696688760

**Comment by Ecens** [comment]
Tried it, it works perfectly now. Thank your for everything
