### ISSUE TITLE
about editing db.json file

### ISSUE THREAD

**Issue by crownlvl999** [MishaProductions/nikke-server#9]
hello Misha, thank you so much for your work 

can you please tell us how to permanently edit the file db.json cause it resets back to default 😅

sorry if it's a dumb question I tried many ways to edit it but it stubbornly is always the same

**Comment by MishaProductions** [comment]
Hello, you have to stop nksrv first before saving your changes.

**Comment by cantrunserverselectordesktopexe** [comment]
after i edited the db file this happened 
![Screenshot (195)](https://github.com/user-attachments/assets/4d99f500-0173-45f5-a527-2e99f10305f2)

**Comment by MishaProductions** [comment]
Your json syntax is wrong
